server:
  port: 9001

spring:
  application:
    name: DEPARTMENT-SERVICE

  zipkin:
    base-url: http://127.0.0.1:9411/

eureka:
  instance:
    hostname: eureka-0
    # hostname: "${HOSTNAME}.eureka"
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      # defaultZone: ${EUREKA_SERVER_ADDRESS}
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
